### ISSUE TITLE
Pics or it didnt happen

### ISSUE THREAD

**Issue by schmijos** [coredump-ch/rpsrtsrs#2]
Could you please put your screenshots into the README? Otherwise your game is worth nothing!

**Comment by rnestler** [comment]
Good point! Will do that as soon as possible :smile:

**Comment by schmijos** [comment]
Began with the galore here: #8

**Comment by rnestler** [comment]
I consider this fixed with 91656e3f0c3c2f15fffeaa14847e901718d07422
