### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by rnestler** [coredump-ch/rpsrtsrs#57]
We should probably add a license to the repository.

### Which license?

 * MIT OR Apache-2.0 (Rust "standard")
 * (A)GPL (Because we maybe want to use GPL'd dependencies)

We will use the [AGPL](https://www.gnu.org/licenses/agpl-3.0.en.html) because MIT doesn't give us much advantage since it is not a library. Also it enables us to use GPL'd dependencies. We use AGPL so nobody may run a modified version on a server without publishing the source.

### License of current dependencies

 * [rand](https://crates.io/crates/rand) MIT/Apache-2.0
 * [piston](https://crates.io/crates/piston) MIT
 * [bincode](https://crates.io/crates/bincode) MIT
 * [serde](https://crates.io/crates/serde) MIT/Apache-2.0
 * [docopt](https://crates.io/crates/docopt) Unlicense/MIT

### Agreement of contributors

I agree that my past and future contributions are licensed under the conditions of the [AGPL](https://www.gnu.org/licenses/agpl-3.0.en.html).

 - [x] @dbrgn
 - [x] @schmijos
 - [x] @rnestler
 - [x] @das-g

**Comment by dbrgn** [comment]
I'm in favor of MIT/Apache-2.0 dual licensing.

Edit: Although GPL could be reasonable too, for a game. It's not a library, so we'd probably want the source of all contributions to be available.

**Comment by rnestler** [comment]
I think I would go with GPL for this one. Can please everybody state if they are OK with that?

**Comment by dbrgn** [comment]
I'm in favor. Note: I'd actually choose the AGPL, since the game could be served over the network.

**Comment by rnestler** [comment]
> I'm in favor. Note: I'd actually choose the AGPL, since the game could be served over the network.

OK, AGPL it is :+1:

**Comment by dbrgn** [comment]
@schmijos and @das-g missing :)

**Comment by das-g** [comment]
AGPL is fine with me. :+1:

**Comment by rnestler** [comment]
@schmijos Did you tick yourself off in the summary above? Because if yes I'll merge the pull-request.

**Comment by rnestler** [comment]
@schmijos confirmed to me that he did in fact tick himself off in the summary above.
